/* Stay Strong — offline photo demos.
 * Start/end position photographs from free-exercise-db
 * (https://github.com/yuhonas/free-exercise-db, public domain / Unlicense),
 * stored in img/demo/<exercise-id>-0.jpg and -1.jpg. Generated file. */

const DEMO_PHOTOS = {
  "sh-press-machine": "Leverage Shoulder Press",
  "sh-db-press": "Dumbbell Shoulder Press",
  "sh-smith-press": "Smith Machine Overhead Shoulder Press",
  "sh-lat-raise-machine": "Side Lateral Raise",
  "sh-db-lat-raise": "Side Lateral Raise",
  "sh-cable-lat-raise": "Cable Seated Lateral Raise",
  "sh-reverse-pec-deck": "Reverse Machine Flyes",
  "sh-face-pull": "Face Pull",
  "sh-front-raise": "Front Dumbbell Raise",
  "sh-arnold-press": "Arnold Dumbbell Press",
  "sh-bb-press": "Standing Military Press",
  "sh-lean-raise": "One-Arm Side Laterals",
  "sh-cross-cable-rear": "Cable Rear Delt Fly",
  "sh-plate-raise": "Front Plate Raise",
  "bk-lat-pulldown": "Wide-Grip Lat Pulldown",
  "bk-seated-row": "Seated Cable Rows",
  "bk-assisted-pullup": "Band Assisted Pull-Up",
  "bk-chest-row": "Leverage Iso Row",
  "bk-db-row": "One-Arm Dumbbell Row",
  "bk-straight-arm": "Straight-Arm Pulldown",
  "bk-tbar-row": "T-Bar Row with Handle",
  "bk-back-ext": "Hyperextensions (Back Extensions)",
  "bk-shrug": "Dumbbell Shrug",
  "bk-close-pulldown": "V-Bar Pulldown",
  "bk-machine-highrow": "Leverage High Row",
  "bk-single-cable-row": "Seated One-arm Cable Pulley Rows",
  "bk-bb-row": "Bent Over Barbell Row",
  "lg-leg-press": "Leg Press",
  "lg-hack-squat": "Hack Squat",
  "lg-smith-squat": "Smith Machine Squat",
  "lg-leg-ext": "Leg Extensions",
  "lg-leg-curl": "Seated Leg Curl",
  "lg-rdl": "Stiff-Legged Dumbbell Deadlift",
  "lg-lunges": "Dumbbell Lunges",
  "lg-seated-calf": "Seated Calf Raise",
  "lg-standing-calf": "Standing Calf Raises",
  "lg-adductor": "Thigh Adductor",
  "lg-goblet-squat": "Goblet Squat",
  "lg-bulgarian": "Split Squat with Dumbbells",
  "lg-hip-thrust": "Barbell Hip Thrust",
  "lg-lying-curl": "Lying Leg Curls",
  "lg-legpress-calf": "Calf Press On The Leg Press Machine",
  "ch-press-machine": "Leverage Chest Press",
  "ch-bench-press": "Barbell Bench Press - Medium Grip",
  "ch-incline-db": "Incline Dumbbell Press",
  "ch-smith-incline": "Smith Machine Incline Bench Press",
  "ch-pec-deck": "Butterfly",
  "ch-cable-cross": "Cable Crossover",
  "ch-dips": "Dips - Chest Version",
  "ch-pushup": "Pushups",
  "ch-flat-db-press": "Dumbbell Bench Press",
  "ch-smith-flat": "Smith Machine Bench Press",
  "ch-low-cable-fly": "Low Cable Crossover",
  "ch-flat-fly": "Dumbbell Flyes",
  "ar-ez-curl": "EZ-Bar Curl",
  "ar-preacher": "Machine Preacher Curls",
  "ar-hammer": "Hammer Curls",
  "ar-cable-curl": "Cable Hammer Curls - Rope Attachment",
  "ar-incline-curl": "Incline Dumbbell Curl",
  "ar-pushdown": "Triceps Pushdown - Rope Attachment",
  "ar-overhead-ext": "Cable Rope Overhead Triceps Extension",
  "ar-dip-machine": "Dip Machine",
  "ar-skull": "EZ-Bar Skullcrusher",
  "ar-bench-dip": "Bench Dips",
  "ar-concentration": "Concentration Curls",
  "ar-spider-curl": "Spider Curl",
  "ar-cgbp": "Close-Grip Barbell Bench Press",
  "ar-db-overhead": "Dumbbell One-Arm Triceps Extension",
  "ar-kickback": "Tricep Dumbbell Kickback",
  "lg-cable-kickback": "One-Legged Cable Kickback",
  "lg-abductor": "Thigh Abductor",
  "lg-step-up": "Step-up with Knee Raise",
  "lg-sumo-squat": "Plie Dumbbell Squat",
  "co-plank": "Plank",
  "co-dead-bug": "Dead Bug",
  "co-cable-crunch": "Cable Crunch",
  "co-hanging-knee": "Hanging Leg Raise",
  "co-mountain-climber": "Mountain Climbers",
  "co-bicycle": "Air Bike",
  "sh-handstand-hold": "Handstand Push-Ups",
  "bk-pullup": "Pullups",
  "bk-chinup": "Chin-Up",
  "bk-inverted-row": "Inverted Row",
  "bk-inverted-row-under": "Inverted Row",
  "bk-superman": "Superman",
  "lg-bw-squat": "Bodyweight Squat",
  "lg-pistol": "Kettlebell Pistol Squat",
  "lg-reverse-lunge": "Dumbbell Rear Lunge",
  "lg-bw-bulgarian": "Split Squats",
  "lg-glute-bridge": "Butt Lift (Bridge)",
  "lg-sl-glute-bridge": "Single Leg Glute Bridge",
  "lg-nordic": "Natural Glute Ham Raise",
  "lg-bw-calf": "Standing Dumbbell Calf Raise",
  "lg-jump-squat": "Freehand Jump Squat",
  "ch-decline-pushup": "Decline Push-Up",
  "ch-diamond-pushup": "Push-Ups - Close Triceps Position",
  "ch-wide-pushup": "Pushups (Close and Wide Hand Positions)",
  "ch-bar-dips": "Parallel Bar Dip",
  "ch-incline-pushup": "Incline Push-Up",
  "sh-bent-rear-fly": "Reverse Flyes",
  "bk-db-pullover": "Straight-Arm Dumbbell Pullover",
  "bk-two-db-row": "Bent Over Two-Dumbbell Row",
  "lg-db-calf": "Standing Dumbbell Calf Raise",
  "ch-floor-press": "Dumbbell Floor Press",
  "ar-db-curl": "Dumbbell Bicep Curl",
  "ar-db-skull": "Lying Dumbbell Tricep Extension",
  "sh-handstand-pushup": "Handstand Push-Ups",
  "sh-arm-circles": "Arm Circles",
  "ar-body-tricep-press": "Body Tricep Press",
  "ar-triceps-dip": "Dips - Triceps Version",
  "ar-negative-chinup": "Chin-Up",
  "ar-chinup-hold": "Chin-Up",
  "bk-scap-pullup": "Scapular Pull-Up",
  "bk-feet-elevated-row": "Inverted Row",
  "ch-plyo-pushup": "Plyo Push-up"
};
