/* Stay Strong — curated form videos, one per exercise.
 * Each ▶ Video button deep-links to its exact YouTube video, so a video
 * downloaded in the YouTube app (YouTube Premium) plays with no signal.
 * NASM = National Academy of Sports Medicine's official technique series. */

const FORM_VIDEOS = {
  /* shoulders */
  'sh-press-machine':    { id: 'BAZkFGeUy5U', title: 'Shoulder Press Machine — tutorial for gym beginners' },
  'sh-db-press':         { id: 'qEwKCR5JCog', title: 'How To: Dumbbell Shoulder Press' },
  'sh-smith-press':      { id: 'flnw6LPN5oM', title: 'Smith Machine Overhead Press — how to' },
  'sh-lat-raise-machine':{ id: 'IropE3iOk2c', title: 'Machine Lateral Raise — proper form' },
  'sh-db-lat-raise':     { id: 'XPPfnSEATJA', title: 'Dumbbell Lateral Raise (NASM)' },
  'sh-cable-lat-raise':  { id: 'zpbm-xRHB6k', title: 'Cable Lateral Raise — proper form' },
  'sh-reverse-pec-deck': { id: 'v0rJuhEa59c', title: 'Reverse Pec Deck Fly — proper form' },
  'sh-face-pull':        { id: 'eTCBSFlCJ_s', title: 'Face Pull (NASM)' },
  'sh-front-raise':      { id: '-t7fuZ0KhDA', title: 'How To: Dumbbell Front Raise' },
  'sh-arnold-press':     { id: 'EyqMRSyfV0M', title: 'How To: Arnold Press' },
  'sh-bb-press':         { id: 'bMksDb5a3P0', title: 'Standing Barbell Overhead Press — form & safety' },
  'sh-lean-raise':       { id: 'qWif_7SOYpQ', title: 'Leaning Lateral Raise — tutorial' },
  'sh-cross-cable-rear': { id: 'ywMSCem375A', title: 'Cross Cable Rear Delt Fly — form tutorial' },
  'sh-plate-raise':      { id: 'HN8HYJTOl8c', title: 'How To Do Front Plate Raises' },

  /* back */
  'bk-lat-pulldown':     { id: 'CAwf7n6Luuc', title: 'How To: Lat Pulldown — 3 golden rules' },
  'bk-seated-row':       { id: '0R9ZQd3aM6s', title: 'How to do a Seated Row (NASM)' },
  'bk-assisted-pullup':  { id: 'fnHeovkmkkk', title: 'Assisted Pull-Up Machine — form, setup & safety' },
  'bk-chest-row':        { id: 'yFo-EFYzf1s', title: 'Chest Supported Row Machine — good form' },
  'bk-db-row':           { id: 'pYcpY20QaE8', title: 'How To: Single-Arm Dumbbell Row' },
  'bk-straight-arm':     { id: 'WDOV2PDpkiU', title: 'Straight Arm Pulldown — actually feel your lats' },
  'bk-tbar-row':         { id: 'BbBR3v2UShw', title: 'Standing T-Bar Row — proper form' },
  'bk-back-ext':         { id: 'cFNs7A3_oeI', title: 'How To Do 45 Degree Back Extensions' },
  'bk-shrug':            { id: 'cJRVVxmytaM', title: 'How To: Dumbbell Shrugs' },
  'bk-close-pulldown':   { id: 'mUoo2l-p8Hw', title: 'Close Grip Lat Pulldown — technique & tips' },
  'bk-machine-highrow':  { id: 'beKbbq6NhWY', title: 'Machine High Row (Hammer Strength) — guide' },
  'bk-single-cable-row': { id: 'CrylzZHfO1c', title: 'Single Arm Seated Cable Row — how to' },
  'bk-bb-row':           { id: 'Lf4LUL3FeUM', title: 'Barbell Bent-Over Row — form, cues & mistakes' },

  /* legs */
  'lg-leg-press':        { id: 'cDGOn-yfKJA', title: 'How to do a Leg Press (NASM)' },
  'lg-hack-squat':       { id: '-lAnEGH2blE', title: 'How to Do the Hack Squat' },
  'lg-smith-squat':      { id: 'AHnX-aimA4E', title: 'How To: Smith Machine Squat' },
  'lg-leg-ext':          { id: '4zOky6-n78I', title: 'Leg Extension — proper form' },
  'lg-leg-curl':         { id: '14OrOWlM5QU', title: 'Seated Leg Curl — proper form' },
  'lg-rdl':              { id: 'aa57T45iFSE', title: 'Dumbbell Romanian Deadlift (NASM)' },
  'lg-lunges':           { id: 'I34ysEkPK7w', title: 'Dumbbell Walking Lunge — how to' },
  'lg-seated-calf':      { id: 'I1uQtobaNRQ', title: 'Seated Calf Raise — proper form' },
  'lg-standing-calf':    { id: '4HQ8Am9IuME', title: 'Standing Calf Raise — proper form' },
  'lg-adductor':         { id: 'ScqpbvOZWe8', title: 'Hip Adduction Machine — how to' },
  'lg-goblet-squat':     { id: 'nfX7IFK9UNI', title: 'Goblet Squat (NASM)' },
  'lg-bulgarian':        { id: 'hbw7hdyOpq0', title: 'Bulgarian Split Squat (NASM)' },
  'lg-hip-thrust':       { id: 'eutQE64svRE', title: 'Barbell Hip Thrust — step by step' },
  'lg-lying-curl':       { id: 'lUH80pneL5w', title: 'Lying Leg Curl (NASM)' },
  'lg-legpress-calf':    { id: '8k435cj30gc', title: 'Leg Press Calf Raise (NASM)' },

  /* chest */
  'ch-press-machine':    { id: 'sqNwDkUU_Ps', title: 'How To Use The Chest Press Machine' },
  'ch-bench-press':      { id: 'CayG6UYqL8g', title: 'Barbell Bench Press (NASM)' },
  'ch-incline-db':       { id: 'JKnpHchOWPU', title: 'Incline Dumbbell Chest Press (NASM)' },
  'ch-smith-incline':    { id: 'b8DqTO6ak0k', title: 'How To: Smith Machine Incline Bench Press' },
  'ch-pec-deck':         { id: 'hZ0CGRaKwbQ', title: 'Pec Deck / Chest Fly — how to' },
  'ch-cable-cross':      { id: 'XY6JrX1wyxk', title: 'Cable Crossover (NASM)' },
  'ch-dips':             { id: 'kbmVlw-i0Vs', title: 'Assisted Dips — exercise tutorial' },
  'ch-pushup':           { id: 'WDIpL0pjun0', title: 'Push-Up (NASM)' },
  'ch-flat-db-press':    { id: 'Y_7aHqXeCfQ', title: 'How To: Dumbbell Bench Press — 3 golden rules' },
  'ch-smith-flat':       { id: 'z_r6hDOYtO0', title: 'How To: Smith Machine Bench Press' },
  'ch-low-cable-fly':    { id: 'eQ_NBB6OBH4', title: 'Low-To-High Cable Fly — perfect form' },
  'ch-flat-fly':         { id: 'eozdVDA78K0', title: 'How To: Dumbbell Flys On A Flat Bench' },

  /* arms */
  'ar-ez-curl':          { id: '5NsFLGUf0Fo', title: 'EZ Bar Curl — perfect form' },
  'ar-preacher':         { id: 'to3m8zws1n8', title: 'Machine Preacher Curl — how to' },
  'ar-hammer':           { id: 'zC3nLlEvin4', title: 'How To: Dumbbell Hammer Curl' },
  'ar-cable-curl':       { id: 'VY4walmoM-I', title: 'Cable Hammer Curls — tutorial' },
  'ar-incline-curl':     { id: '1gCfaEWk_Ds', title: 'Incline Dumbbell Curl — form tutorial' },
  'ar-pushdown':         { id: 'qHDrQglWgS4', title: 'Cable Rope Pushdown — tutorial' },
  'ar-overhead-ext':     { id: '8WC7rIOkhi0', title: 'Cable Overhead Tricep Extension — how to' },
  'ar-dip-machine':      { id: 'snKz3KZw6GA', title: 'Tricep Dip Machine — proper form' },
  'ar-skull':            { id: 'GaK2da6B2zM', title: 'EZ Bar Skull Crushers — how to' },
  'ar-bench-dip':        { id: 'WVeZDBhZwLA', title: 'Bench Dip (NASM)' },
  'ar-concentration':    { id: 'Jvj2wV0vOYU', title: 'How To: Dumbbell Concentration Curl' },
  'ar-spider-curl':      { id: 'OK6vpxXZ2pk', title: 'How To: Prone Incline Curl (Spider Curl)' },
  'ar-cgbp':             { id: 'LJeqLAmJLfs', title: 'Close Grip Bench Press — proper form' },
  'ar-db-overhead':      { id: 'kZ-ReOdn2qk', title: 'Seated Single-Arm Dumbbell Tricep Extension' },
  'ar-kickback':         { id: '6SS6K3lAwZ8', title: 'How To: Tricep Kickback (Dumbbell)' },

  /* glutes */
  'lg-cable-kickback':   { id: 'bVrmtCI00Ys', title: 'Cable Kickback (Glute Max) — form tutorial' },
  'lg-abductor':         { id: 'soaTR1UtEw0', title: 'Hip Abductor Machine — how to' },
  'lg-step-up':          { id: 'tqECKZxlCKE', title: 'Dumbbell Step-Ups — master proper form' },
  'lg-sumo-squat':       { id: 'YYpq4fkl308', title: 'Dumbbell Sumo Squat — perfect form' },

  /* core */
  'co-plank':            { id: 'mwlp75MS6Rg', title: 'Plank (NASM)' },
  'co-dead-bug':         { id: 'bxn9FBrt4-A', title: 'Dead Bug (NASM)' },
  'co-cable-crunch':     { id: '0KEP6A1deBE', title: 'Kneeling Cable Crunch — tutorial' },
  'co-hanging-knee':     { id: 'G6a5267YpHM', title: 'Hanging Knee Raise — proper form' },
  'co-mountain-climber': { id: 'BhERlhtzQ1s', title: 'Mountain Climbers — proper form' },
  'co-bicycle':          { id: 'Mwo0pNv5EG8', title: 'Bicycle Crunch — NASM CPT' },

  /* calisthenics */
  'sh-pike-pushup':      { id: '2b5t0Cu2nQI', title: 'Pike Push-Up (NASM)' },
  'sh-handstand-hold':   { id: '2v1YDTzMcO8', title: 'How To Do Wall Handstand Hold' },
  'sh-prone-y':          { id: '30fhlXpEZxw', title: 'Prone Rear Delt Y Flyes' },
  'bk-pullup':           { id: '9yVGh3XbJ34', title: 'Pull-Up (NASM)' },
  'bk-chinup':           { id: 'e1YSApl-QcM', title: 'Perfect Chin-Ups — full guide' },
  'bk-inverted-row':     { id: 'ytFnYaoIkSg', title: 'Inverted Row — exercise guide' },
  'bk-inverted-row-under': { id: '2wQU1Klfc6U', title: 'Underhand Inverted Row' },
  'bk-superman':         { id: 'z6PJMT2y8GQ', title: 'Superman — exercise tutorial' },
  'lg-bw-squat':         { id: 'P-yaD24bUE8', title: 'Bodyweight Squat — proper form' },
  'lg-pistol':           { id: '6pUx2ktKCMQ', title: 'Assisted Pistol Squats — proper form' },
  'lg-reverse-lunge':    { id: 'u_zSfK5ZFU4', title: 'Reverse Lunge — proper form' },
  'lg-bw-bulgarian':     { id: 'VPhhE6bBzZE', title: 'How To Do Bulgarian Split Squats Correctly' },
  'lg-glute-bridge':     { id: 'nbjJjSa0cKo', title: 'How To Do a Glute Bridge Correctly' },
  'lg-sl-glute-bridge':  { id: 'VUl8R0kn6v4', title: 'Single Leg Glute Bridge — proper form' },
  'lg-nordic':           { id: 'gnb_hAG1dGY', title: 'Nordic Hamstring Curl — beginner regression' },
  'lg-bw-calf':          { id: 'Wh8EXjjr6JU', title: 'Bodyweight Calf Raises' },
  'lg-jump-squat':       { id: 'tZSYZdtbONc', title: 'Squat Jump (NASM)' },
  'ch-decline-pushup':   { id: 'DBz85WuXqMk', title: 'Decline Push-Up (NASM)' },
  'ch-diamond-pushup':   { id: '2-OFbQ9GLpE', title: 'Diamond Push Ups — correct form' },
  'ch-wide-pushup':      { id: 'Z8nUVpSZAhE', title: 'Wide Grip Push Up — demonstration' },
  'ch-bar-dips':         { id: '85u_8mz5lBA', title: 'Parallel Bar Dips — perfect form & mistakes' },
  'ch-incline-pushup':   { id: '0JUrOH--Kdk', title: 'Incline Push-Up (NASM)' },

  /* free weights */
  'sh-bent-rear-fly':    { id: 'Lec8GC1SiS8', title: 'Rear Delt Bent Over Flies — how to' },
  'bk-db-pullover':      { id: 'Qc4L9I3pHnw', title: 'Dumbbell Pullovers — back tutorial' },
  'bk-two-db-row':       { id: 'DJfQN6xJL28', title: 'Dumbbell Bent Over Row — how to' },
  'lg-db-calf':          { id: 'H6WptvjXkgw', title: 'Dumbbell Standing Calf Raises' },
  'ch-floor-press':      { id: 'uUGDRwge4F8', title: 'How To: Dumbbell Floor Press' },
  'ar-db-curl':          { id: 'd_TfENBv38s', title: 'How To: Standing Dumbbell Bicep Curl' },
  'ar-db-skull':         { id: 'MO_03opCc0g', title: 'Lying Dumbbell Tricep Extension — how to' },

  /* calisthenics shoulders + arms (2.0) */
  'sh-handstand-pushup':    { id: '6MdyYIRS7FY', title: 'How to Wall Handstand Push-Up (School of Calisthenics)' },
  'sh-arm-circles':         { id: '4TJv9YmECjc', title: 'How to Do: Arm Circles' },
  'sh-lateral-plank-walk':  { id: '9XMy6LDsHSU', title: 'How to Do Lateral Plank Walk' },
  'sh-wall-lateral-iso':    { id: '9e8XplPoasE', title: 'Isometric Shoulder Raise against a wall' },
  'sh-prone-t':             { id: 'WNnLKAvHZfo', title: 'Prone Rear Delt Raise' },
  'ar-body-tricep-press':   { id: 'ACyLmO9wj98', title: 'How to Bodyweight Tricep Extension (calisthenics)' },
  'ar-triceps-dip':         { id: 'J3WYrjNDLI4', title: 'The best way to do Triceps Dips on parallel bars' },
  'ar-negative-chinup':     { id: 'Ve6-GZJmd1M', title: 'The Negative Chin-Up: how to' },
  'ar-chinup-hold':         { id: 'ogc7DN4rRqI', title: 'Isometric Chin-Up Holds' },
  'ar-bw-curl':             { id: 'cr1Vm1ClckU', title: 'Bodyweight Bicep Curl tutorial' },

  /* calisthenics back, chest, calves (2.0) */
  'bk-scap-pullup':         { id: '-ZIpSoTRsuE', title: 'Scapular Pull-Ups (beginner to advanced)' },
  'bk-feet-elevated-row':   { id: '7GYfJuoEsbQ', title: 'Feet Elevated Inverted Row' },
  'bk-towel-door-row':      { id: '62NT4yA4igM', title: 'Towel Rows at home — bodyweight back' },
  'ch-plyo-pushup':         { id: 'FRo3b_Pfw3M', title: 'How to Do a Plyo Push-Up & Clap Push-Up' },
  'ch-archer-pushup':       { id: 'MxVbNel13Ek', title: 'Archer Push-Ups tutorial with progressions' },
  'ch-sliding-fly':         { id: 'pxKvc2Lc2lc', title: 'How to do a Slider Push-Up Fly' },
  'lg-sl-calf':             { id: 'IphGZ8OlfYg', title: 'How to do a Single-Leg Calf Raise' },
};
